### ISSUE TITLE
Doesnt work with xaeros minimap fairplay edition

### ISSUE THREAD

**Issue by Beerandoo** [lack/way2wayfabric#1]
![image](https://github.com/lack/way2wayfabric/assets/137313823/783f5600-b205-47cc-a21e-e0175d1627f8)

i get this error although i am using a greater version of xaeros minimap, its just that im using fairplay edition instead of the regular edition

**Comment by Beerandoo** [comment]
Is there any plans in making it compatible with the xaeros minimap fairplay edition of the mod?

**Comment by lack** [comment]
That's a good idea.

I'll try to figure that out soon!

**Comment by lack** [comment]
Just released v0.0.5 on modrinth and curseforge which now allows the fair-play edition of Xaero's Minimap!

Thanks for the feedback!
