### ISSUE TITLE
Waypoint manager randomly stops working.

### ISSUE THREAD

**Issue by Slayer5934** [lack/way2wayfabric#2]
`(Way2WayFabric) Waypoint manager is not ready after 21 attempts. Giving up and discarding 1 deferred events`

The waypoint manager will stop working after a while with the error above in the log and no new waypoints are added, usually happens after going into a new world after being in another but happens on first game as well rarely.

**Comment by Slayer5934** [comment]
I have noticed the waypoint manager try count does not reset after it successfully starts on another world, so eventually it will always fail.

**Comment by lack** [comment]
Thanks!  I'll try to get to this soon.

Or if you want to submit a PR with the change, it'll probably be sooner ;)

**Comment by Slayer5934** [comment]
https://github.com/lack/way2wayfabric/pull/3 here you go, hopefully I did it right :p

**Comment by lack** [comment]
Looks great, thanks! I'll try to do a new build tomorrow!

**Comment by lack** [comment]
Released v0.0.5 on modrinth and curseforge, which contains this fix.

Thanks so much for the contribution!

**Comment by Riley-IsBad** [comment]
Same bug seems to occur using v0.0.6 with Xaero's Minimap version 23.9.3 and Fabric Waystones 3.3.2+MC1.20.1.
`[19:31:21] [Deferred Events/WARN]: Waypoint manager is not ready after 25 attempts. Giving up and discarding 9 deferred events`
Full log can be found [here](https://mclo.gs/u8BKZav)

There does seem to be a lot of instances of lines such as
`[19:31:16] [Server thread/INFO]: Adding waystone fwaystones:village_waystone to village kaisyn:village/flower_forest_japanese/houses`
`[19:31:16] [Server thread/ERROR]: Cannot add to kaisyn:village/flower_forest_japanese/houses as it cannot be found!`
I don't really understand what's going on here, I think Fabric Waystones is trying to add waystone generation to generated structures from mods that I don't have installed, and maybe this is overwhelming the waypoint manager? Seriously pulling that idea outta my ass but I just wanted to mention it in case it was relevant.
